name: Deploy

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: echo "${{ secrets.NAME}}"

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"
